on:
  pull_request:
    types: [assigned]

jobs:
  add-in-review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v4
        with:
          script: |
            await require('.github/workflows/label_add_in_review.js')()
