on:
  pull_request:
    types: [opened, assigned, ready_for_review]
  pull_request_review:
    types: [submitted]

jobs:
  set-labels:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/github-script@v4
        with:
          script: |
            const script = require('.github/workflows/labels.js');
            await script({github, context});
